import { FeedbackItem, TelegramConfig, Department } from '../types';

export const sendNewFeedbackAlert = async (item: FeedbackItem, config: TelegramConfig) => {
    if (!config.botToken || !config.chatId) return;

    const emoji = item.type === 'Жалоба' ? '🚨' : '💡';
    const urgencyIcon = item.urgency === 'Срочно' ? '🔥' : 'ℹ️';

    const message = `
${emoji} <b>New Artwin Feedback</b>

<b>Department:</b> ${item.department}
<b>Type:</b> ${item.type}
<b>From:</b> ${item.role} ${item.isAnonymous ? '(Anonymous)' : ''}
<b>Urgency:</b> ${item.urgency} ${urgencyIcon}

<b>Message:</b>
<i>${item.message}</i>

${item.contact ? `<b>Contact:</b> ${item.contact}` : ''}
    `.trim();

    await sendToTelegram(message, config);
};

export const sendManagementReport = async (reportText: string, dept: Department, config: TelegramConfig) => {
    if (!config.botToken || !config.chatId) return;

    const message = `
📊 <b>Artwin Executive Report</b>
Target: ${dept} Manager

${reportText}

<i>Generated by Gemini AI</i>
    `.trim();

    await sendToTelegram(message, config);
};

const sendToTelegram = async (text: string, config: TelegramConfig) => {
    try {
        const url = `https://api.telegram.org/bot${config.botToken}/sendMessage`;
        await fetch(url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                chat_id: config.chatId,
                text: text,
                parse_mode: 'HTML'
            })
        });
    } catch (error) {
        console.error('Failed to send Telegram message', error);
    }
};